#!/bin/bash

git_branch="$(echo $1 | awk 'NR==1 {print $3}')"
echo $1 >~/aaa
state=""
case $1 in
  *modified:* ) state+="!" ;;
  *Untracked* ) state+="?" ;;
  *deleted* ) state+="✘" ;;
  *new\ file* ) state+="+" ;;
  *ahead* ) state+="⇡" ;;
  *behind* ) state+="⇣" ;;
  *diverged* ) state+="⇕" ;;
  *conflicts* ) state+="=" ;;
esac
git_info="$git_branch $state"

echo $git_info
